# Generated by Django 3.1.2 on 2020-10-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrelsighting',
            name='uid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrelsighting',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Adult', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrelsighting',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), ('', '')], default='', help_text='Whether squirrel was sighted on or above ground level', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrelsighting',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='PM', max_length=50),
        ),
    ]
