# Generated by Django 3.1.2 on 2020-10-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20201015_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrelsighting',
            name='uid',
        ),
    ]
